# -*- coding: utf-8 -*-
"""Tessract

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19TvRx8qbAy581LVqOypKd95K2QaO129Q
"""

!sudo apt install tesseract-ocr
!pip install pytesseract

import pytesseract
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

from google.colab import files
uploaded = files.upload()

image_path_in_colab="/content/Demo 2.jpg"
extractedInformation = pytesseract.image_to_string(Image.open("/content/Demo 2.jpg"))
print(extractedInformation)