# -*- coding: utf-8 -*-
"""Tessract

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19TvRx8qbAy581LVqOypKd95K2QaO129Q
"""

!pip install tesseract

import pytesseract
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

from google.colab import files
uploaded = files.upload()

image_path="/content/Invoice1.jpeg,/content/Invoice2.jpeg"
extractedInformation = pytesseract.image_to_string(Image.open("/content/Invoice1.jpeg"))
print(extractedInformation)

image_path="/content/Invoice1.jpeg,/content/Invoice2.jpeg"
extractedInformation = pytesseract.image_to_string(Image.open("/content/Invoice2.jpeg"))
print(extractedInformation)